base_url = "https://jasonfried.info"
title = "Jason Fried"
description = "Writer, rancher, occasional thinker."
default_language = "en"
compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
author = "Jason Fried"
